#!/bin/sh
#set -x

# Copyright (C) 2015 by Paul Seelig <wmlive@rumbero.org>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

LANG=C

if [ "$(/usr/bin/id -u)" != "0" ]
then
    echo "Sorry, only root or authorized users can do this"
    exit 0
fi

PROGENVDEFAULTS=/etc/default/progfetch

if [ -s ${PROGENVDEFAULTS} ]
then
   . ${PROGENVDEFAULTS}
fi

PMOONFETCH=/usr/sbin/pmoonfetch
FOSSAFETCH=/usr/sbin/fsmlfetch
TBRDFETCH=/usr/sbin/tbrdfetch
TLGRMFETCH=/usr/sbin/tlgrmfetch
FFOXFETCH=/usr/sbin/ffoxfetch

if [ "${INSTALLPROGS}" != "" ]
then
    for PROGCHOICE in ${INSTALLPROGS}
    do
        if [ "${PROGCHOICE}" = "palemoon" ]
        then
            ${PMOONFETCH}
        elif [ "${PROGCHOICE}" = "FossaMail" ]
        then
            ${FOSSAFETCH}
        elif [ "${PROGCHOICE}" = "thunderbird" ]
        then
            ${TBRDFETCH}
        elif [ "${PROGCHOICE}" = "telegram" ]
        then
            ${TLGRMFETCH}
        elif [ "${PROGCHOICE}" = "firefox" ]
        then
            ${FFOXFETCH}
        else
            echo Unable to fetch "${PROGCHOICE}"
        fi
        echo ""
    done
fi
